### PR TITLE
Additional output file for GMT to build multi-ghe Modelica models

### PR DESCRIPTION
**Pull request by vtnate**
#### Any background context you want to provide?
Multi-ghe districts have additional information that is needed to build a Modelica model appropriately
#### What does this PR accomplish?
Generates additional json file with loop order information for the GMT & REopt to consume
#### How should this be manually tested?
- Run [the 13-building test](https://github.com/NREL/ThermalNetwork/blob/multi-ghe/thermalnetwork/tests/test_network.py#L82)
- Confirm `_loop_order.json` file is created/updated next to the sys-param file
    - Since this is generated by the code every time the test is run, should it be git-ignored?
- Confirm the test passes
- Confirm the contents of those files hold the appropriate information

### CODE REVIEW

**Review by JingWang-CUB — APPROVED** [review]
These changes look good to me. I've tested them on my end and they work as expected.

**Comment by mitchute** [comment]
What is the reason for removing the files in the tests? Furthermore, shouldn't we be testing *something* related to make sure they are accurate?

**Comment by vtnate** [comment]
> What is the reason for removing the files in the tests? Furthermore, shouldn't we be testing _something_ related to make sure they are accurate?

No real reason to delete the test files. I'm a big fan of testing, I'll think about that a bit more. I haven't yet come up with a way to test it that isn't identical to what the real code is doing. Thank you!

**Comment by mitchute** [comment]
I don't think we need to complicate it, but it would be good to assert some simple tests against these files. If needed, there's the `tempfile` library that provides a platform-agnostic way to create temporary directories where we can write files, test, and then forget them.

**Review by mitchute — APPROVED** [review]
Thanks for adding these checks! Looks great.

**Pull request merged**
