### PR TITLE
Change CI to run on PR activity instead of push

### PR DESCRIPTION
**Pull request by vtnate**
### Any background context you want to provide?
CI wasn't running automatically when PRs are made from a fork of the repo. This PR should fix that
### What does this PR accomplish?
- Update GHA workflow files to run CI on pull_request activity, not on push. Push appears to not pick up activity from a fork of the repo

### CODE REVIEW

**Comment by chriswmackey** [comment]
FYI, @vtnate , it might be nice to run the tests on both push and pull request. I know that this is what we do for all of our actions in Ladybug Tools. Here's a sample:

https://github.com/ladybug-tools/dragonfly-energy/blob/master/.github/workflows/ci.yaml#L4

The call is obviously up to you but, with the tests running on both commits and PRs, it makes it almost impossible for us to release a version that doesn't pass the tests.

**Comment by vtnate** [comment]
Thanks @chriswmackey. Running on pull_request, if I understand correctly, means the workflow should fire at every action in a PR. However, you bring up a good point that sometimes irresponsible people (me) push directly to the repo without making a PR, and my current setup would not catch that. Hummmmmm. Do you accidentally get double-runs when a push is made to a PR with that setting?

**Comment by vtnate** [comment]
There we go. We do get double-runs when both are set. I think I like having it on `pull_request` only. I'll just have to clean up my own behavior and use PRs for everything 😆 .

**Review by mitchute — APPROVED** [review]

**Comment by chriswmackey** [comment]
Yes, you will get one run when the PR is opened and another when it's merged. Our unit tests run pretty quickly so I realize the case is different when your tests take longer.

**Comment by mitchute** [comment]
@vtnate looks it looks like I merged this prematurely (the runners aren't picking up the tests), so this probably needs one more update.

**Pull request merged**
